### ISSUE TITLE
Blog RSS/Atom Feed

### ISSUE THREAD

**Issue by tonydero** [FyroxEngine/rg3d.rs#35]
Hello! Any plans for an RSS or Atom feed for the blog? Would be nice to have some way to get notifications when a new one comes out. Would also be great to have different ones for TWiF and the releases.

Apologies if this already exists and I just managed to miss it. I tried all the usual ways of adding `rss`, `atom`, and `feed` to the URL(s).

**Comment by LordCocoNut** [comment]
Ill try to implement it via plugin that exists for vuepress:
https://www.npmjs.com/package/vuepress-plugin-rss-feed

**Comment by mrDIMAS** [comment]
@tonydero RSS feed should be working, please check. Kudos to @LordCocoNut 🎉

**Comment by Barugon** [comment]
What is the RSS URL?

**Comment by mrDIMAS** [comment]
https://fyrox.rs/rss.xml

**Comment by tonydero** [comment]
Working like a charm. Thanks!
